# Generated by Django 6.0.6 on 2026-08-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workload_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workitem",
            name="source",
        ),
    ]
