# Generated by Django 6.0.6 on 2026-07-05 15:14

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0004_document_documentchunk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
